service: bus-timetable
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 900
  region: eu-central-1
  memorySize: 1024

functions:
  main:
    timeout: 30
    handler: dist/serverless.handler
    environment:
      JWT_SECRET: ${env:JWT_SECRET}
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
