service: bus-timetable
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 900
  region: eu-central-1
  memorySize: 1024

functions:
  main:
    timeout: 120
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
